<?php
// Variables
return [
  "creatorName" => "PFTECHNO",
  "creatorUrl" => "https://pftecho.com",
  "creatorWhatsApp" => "+243978333654",
  "creatorEmail" => "conact@pftecho.com",
  "templateName" => "Gestion Finances",
  "templateSuffix" => "Gestion Finances",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Gestion Finances est un logiciel de gestion financière complet qui vous permet de suivre vos finances personnelles et professionnelles, de gérer vos budgets, de générer des rapports financiers détaillés et d'analyser vos dépenses. Il offre une interface conviviale et des fonctionnalités avancées pour vous aider à prendre des décisions financières éclairées.",
  "templateKeyword" => "Gestion finances, logiciel de gestion financière, suivi des finances, gestion des budgets, rapports financiers, analyse des dépenses, interface conviviale, fonctionnalités avancées, décisions financières éclairées",
  "licenseUrl" => "license",
  "livePreview" => "https://demos.quira.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
  "productPage" => "https://pfcecho.com/item/sneat-free-bootstrap-laravel-livewire-starter-kit/",
  "ogTitle" => "Gestion Finances - Logiciel de gestion financière complet",
  "ogType" => "product",
  "ogImage" => "https://github-production-user-asset-6210df.s3.amazonaws.com/61959920/427962312-a4f2c59c-92a0-4624-a0f0-d53ee0acf7d9.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20250328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250328T104541Z&X-Amz-Expires=300&X-Amz-Signature=88f19338f62219496631c44f4da216a3f2da10169fb75377cdc9146dc1722352&X-Amz-SignedHeaders=host",
  "support" => "support",
  "moreThemes" => "https://pfcecho.com/",
  "documentation" => "documentation",
  "repository" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit",
  "gitRepo" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit.git",
  "gitRepoAccess" => "https://tools.quira.com/github/github-access",
  "githubFreeUrl" => "https://github.com/themeselection",
  "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
  "twitterUrl" => "https://x.com/Theme_Selection",
  "githubUrl" => "https://github.com/themeselection",
  "dribbbleUrl" => "https://dribbble.com/themeselection",
  "instagramUrl" => "https://www.instagram.com/themeselection/"
];
